services:
  - type: web
    name: ai-pdf-chatbot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit-app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
